spring.application.name=library-management

#cau hinh ket noi mongodb
spring.mongodb.uri=mongodb://localhost:27017/library_db

server.port=8080

spring.thymeleaf.cache=false

spring.thymeleaf.encoding=UTF-8
spring.messages.encoding=UTF-8

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

logging.level.org.springframework.security=INFO

spring.main.allow-bean-definition-overriding=true

# Test endpoints (disabled by default, enable in dev profile)
app.test-endpoints.enabled=false